### ISSUE TITLE
Breaking Apple M1 change

### ISSUE THREAD

**Issue by Zabrane** [esl/fast_pbkdf2#9]
Hi @NelsonVides 

Would it be possible to put back these compile options:
```erlang
    {"(linux|solaris|freebsd|netbsd|openbsd|dragonfly|darwin|gnu)",
         "CFLAGS", "$CFLAGS -std=c99 -O3 -g -Wall -Wextra -fPIC -I/opt/homebrew/include -I/usr/local/include"},
    {"(linux|solaris|freebsd|netbsd|openbsd|dragonfly|darwin|gnu)",
         "LDLIBS", "$LDLIBS -lcrypto -L/opt/homebrew/lib/ -L/usr/local/lib"},
```
They are important for MacOS (Intel + Apple ARM).
Many thanks

**Comment by NelsonVides** [comment]
Done 🙂
Thanks for raising the issue, you can find the new package release at https://hex.pm/packages/fast_pbkdf2/1.0.5

**Comment by Zabrane** [comment]
Thanks and keep up the good work
